seats:
  name:
    A: [1, 17] # Seat set name, range of seats (e.g A1..A17)
    B: [1, 25]
    C: [1, 26]
    D: [1, 27]
    E: [1, 28] # ↑ closer to front of room
    F: [1, 28] # ↓ closer to back of room
    G: [1, 28]
    H: [1, 28]
    J: [1, 28]
    K: [1, 28]
    L: [1, 28]
    M: [1, 28]
    N: [1, 28]
    P: [1, 28]
    R: [1, 20]
  left_handed: [
      "^R3",
      "^[D-P]7",
      "^[B-C]6",
      "^A4",
      "^A12",
      "^[B-C]20",
      "^[D-P]21",
      "^R17",
    ] # regex matching for left handed seats
  spacing_priority: ["[F-L][1-5]", "[F-L]2[3-8]", "[F-L]1[1-7]"] # priority of seat spacing, earlier in list is higher priority
  filter_unallocated: false # filter out unallocated seats
  filter_seat_dex: false # filter out column which shows if seat is left or right handed
  output_file: "output.csv" # output seating

students:
  file: "students.csv"
  delimiter: "\t"
  dex: "Dexterity" #L = left, R = Right, A = Ambi, this column in "file" which specifies dexterity, can be empty
  filter_fields: [] #fields to be filtered out, fields in the list are not in output
